### ISSUE TITLE
1.1.2 is no longer published in maven

### ISSUE THREAD

**Issue by sdether** [typesafehub/netty-http-pipelining#13]
I'm using

    "com.typesafe.play" % "play-netty-server_2.10" % "2.4.0-M3"

which has a dependency on

     "com.typesafe.netty" % "netty-http-pipelining" % "1.1.2"

This resolved fine when i started the project, but I just handed it over to jenkins and i'm getting

    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	::          UNRESOLVED DEPENDENCIES         ::
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	:: com.typesafe.netty#netty-http-pipelining;1.1.2: not found
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::

And when i check in maven there is only 1.1.4

Is this a mistake or miconfiguration in the publishing pipeline?

I was able to find it through the Typesafe repo but Maven Repository only knows about 1.1.4 and I'd previously resolved 1.1.2 without the Typesafe repo.

http://mvnrepository.com/artifact/com.typesafe.netty/netty-http-pipelining

**Comment by jroper** [comment]
netty-http-pipelining was moved to Maven central in the 1.1.4 release, prior to that, it lived on repo.typesafe.com:

http://repo.typesafe.com/typesafe/releases/com/typesafe/netty/netty-http-pipelining/

repo.typesafe.com was [migrated to bintray](http://repo.typesafe.com/typesafe/releases/com/typesafe/netty/netty-http-pipelining/) a short while ago, there may be some glitches, but looking at the link above, if there were issues, they're now fixed.  If it's still not resolving for you, make sure that repo.typesafe.com is in your resolvers.  The Play SBT plugin adds it automatically, if you're not using that, you'll need to add it manually in your `build.sbt`:

```scala
resolvers += Resolvers.typesafeRepo("releases")
```

**Comment by sdether** [comment]
Thanks. Very confused how I originally resolved it, since I didn't have the typesafe repo until now, but no matter.

**Comment by jroper** [comment]
If you built a Play project with the plugin on your machine first, that would have resolved it, and it would have then been in your ivy cache for the next project.

**Comment by sdether** [comment]
Ah! I bet it got populated when i was playing with some Activator Play templates. Thanks for solving the mystery

**Comment by jroper** [comment]
btw, this is why we've moved it and every other Play dependency to maven central, these problems should disappear once that's complete, hopefully before 2.4.0 is released.

**Comment by pedrorijo91** [comment]
@jroper what is the maven equivalent for `resolvers += Resolver.typesafeRepo("releases")` ?

**Comment by pauldraper** [comment]
Central maven is present by default in sbt.

```sbt 'show resolvers'```

**Comment by phderome** [comment]
Whether I add   `"typesafe-releases" at "https://dl.bintray.com/typesafe/maven-releases"`,
or `Resolver.typesafeRepo("releases")` to resolvers in build.sbt, the result is the same: sbt fails to resolve as sbt.ResolveException: unresolved dependency: com.typesafe.netty#netty-http-pipelining;1.1.2: not found because of some sbt-codacy-coverage issue.
