### ISSUE TITLE
Handling hanging connections

### ISSUE THREAD

**Issue by spinscale** [typesafehub/netty-http-pipelining#7]
Hey,

I've been thinking about how to handle pipelining connections that hang. Maybe I just kept overlooking sth, but if you issue 5 requests via pipelining and the second request hangs indefinately on server side, everything just hangs, right?

Thinking if it would be useful to add some sort of timeout and whenever another request is added into the queue, check if the request we are waiting for is older than the timeout and issue a 50x response?

Does that sound useful or is it useless? Happy to get any feedback here, was just a wild thought so far.

**Comment by jroper** [comment]
@spinscale this should not be implemented by the pipelining handler, but by another handler.  That handler should set a timeout when it receives a request, and if that timeout is exceeded before the response comes, send a 503 error.  You would then have to block all subsequent messages for that handler.  A harder thing to handle would be if the response header had come, but the response body timed out.  Easy for chunked responses, just send a last chunk, but if it's a response with a content length, you would have to send padding bytes to fulfil the promised response content length.

**Comment by spinscale** [comment]
makes sense. closing
